Notebook[{Cell[
CellGroupData[{Cell[
BoxData[RowBox[{"452","/","62"}]],"Input",CellLabel -> "In[1]:= ",
ExpressionUUID -> "b685e718-5f26-4153-aa91-1c8db446a3e4"],Cell[
BoxData[FractionBox[
"226","31"],StandardForm],"Output",CellLabel -> "Out[1]= ",ExpressionUUID -> "217919f4-bc89-4a58-b3c5-4202f3375eab"]},
Open],ExpressionUUID -> "c105e85c-b2ca-4947-8a83-b9160e34585a"],Cell[
CellGroupData[
{Cell[
BoxData[RowBox[{"N","[",FractionBox["226","31"],"]"}]],"Input",NumberMarks -> False,
CellLabel -> "In[2]:= ",ExpressionUUID -> "53220e2a-0f3c-4a75-8d08-c445e2e135fe"],Cell[
BoxData[
"7.290322580645161`",StandardForm],"Output",CellLabel -> "Out[2]= ",ExpressionUUID -> "809d9c85-4a7b-44b2-ae40-649a1d42f5ea"]},
Open],ExpressionUUID -> "dc5d0cdb-06f8-413b-9761-e77028496e7c"],Cell[
CellGroupData[
{Cell[
BoxData[RowBox[{"Rationalize","[","7.290322580645161`","]"}]],"Input",NumberMarks -> False,
CellLabel -> "In[3]:= ",ExpressionUUID -> "bae3794a-b135-4604-8470-a34b6d4aab5e"],Cell[
BoxData[
FractionBox["226","31"],StandardForm],"Output",CellLabel -> "Out[3]= ",ExpressionUUID -> "b7c3149b-aded-4793-b880-5411074a26fa"]},
Open],ExpressionUUID -> "a13f8b56-2d00-450a-9133-22d8a531ff51"],Cell[
CellGroupData[
{Cell[
BoxData[RowBox[{"N","[",RowBox[{RowBox[{FractionBox["226","31"],"-","7.290322580645161`"}],",","16"}],"]"}]],
"Input",NumberMarks -> False,CellLabel -> "In[4]:= ",ExpressionUUID -> "8c320a2a-2325-41a6-a5cf-5f86bf2f194c"],Cell[
BoxData[
"0.`",StandardForm],"Output",CellLabel -> "Out[4]= ",ExpressionUUID -> "ee53d90c-8561-44e4-adaa-df7c8fe8a0c0"]},
Open],ExpressionUUID -> "ae249f9a-82b1-4047-af7e-f710bcf5e35a"],Cell[
CellGroupData[
{Cell[
BoxData[RowBox[{"N","[",RowBox[{RowBox[{FractionBox["226","31"],"-","7.290322580645161`"}],",","20"}],"]"}]],
"Input",NumberMarks -> False,CellLabel -> "In[5]:= ",ExpressionUUID -> "bb05c041-cacd-4a04-ab17-6d59107414b7"],Cell[
BoxData[
"0.`",StandardForm],"Output",CellLabel -> "Out[5]= ",ExpressionUUID -> "ea3728b9-44fd-4467-922f-5afe71d5534a"]},
Open],ExpressionUUID -> "9deb5461-71bf-4dca-a5a0-bbeb876f5214"],Cell[
CellGroupData[
{Cell[
BoxData[RowBox[{"RealDigits","[","0.`","]"}]],"Input",NumberMarks -> False,
CellLabel -> "In[6]:= ",ExpressionUUID -> "b568cf18-f09f-4695-94a7-e40efc154cfe"],Cell[
BoxData[
RowBox[{"{",RowBox[{RowBox[{"{","0","}"}],",",RowBox[{"-","323"}]}],"}"}],StandardForm],
"Output",CellLabel -> "Out[6]= ",ExpressionUUID -> "e44e3cba-ae83-45f2-a021-1febfca0eb87"]},
Open],ExpressionUUID -> "9bd00f9f-59a1-45c4-89bd-e508aa75325c"],Cell[
CellGroupData[
{Cell[
BoxData[RowBox[{"FromDigits","[",RowBox[{"{",RowBox[{RowBox[{"{","0","}"}],",",RowBox[
{"-","323"}]}],"}"}],"]"}]],"Input",NumberMarks -> False,CellLabel -> "In[7]:= ",
ExpressionUUID -> "59068575-1a60-4b75-a68f-ab181381c132"],Cell[
BoxData["0",StandardForm],
"Output",CellLabel -> "Out[7]= ",ExpressionUUID -> "570de4a2-9b38-44e7-84f8-20a0b70c612c"]},
Open],ExpressionUUID -> "59081055-f987-4f06-9332-c6253c6ba75c"]},StyleDefinitions -> "Default.nb",
FrontEndVersion -> "14.1 for Wolfram Cloud 1.69 (July 16, 2024)"]